[package]
name = "typst_vello"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
typst = { workspace = true }
vello = { workspace = true }
vello_svg = { workspace = true }
smallvec = { workspace = true }
ahash = "0.8.11"
ttf-parser = "0.24.1"

[lints]
workspace = true
